# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7941a862d05883c5557fedf72b8441e2148da72e8f4a155e1970ac93ca33a0b9e8b2f3a3dacffc1b69edf555dcf587cd0eb78082bb8ba004084e6a37468cfb2b

test:
  secret_key_base: 210facb0678fda22497fd8d0050ce40eb2a3886b1ae1ea2a652fd01d94473bd4d96b0f9e39994f65f1ad1224891a00a5f10aae50d92557d5c121172f610dc0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
